accelerate launch train_text_to_image_lora_sdxl.py \
 --pretrained_model_name_or_path="stabilityai/stable-diffusion-xl-base-1.0" \
  --pretrained_vae_model_name_or_path="madebyollin/sdxl-vae-fp16-fix" \
  --dataset_name="mary-ruiliii/Genshin-character-portrait-image" \
  --image_column="image" \
  --caption_column="text" \
  --num_train_epochs=300 \
  --validation_prompt="A human Genshin-style character. uses a claymore. has a Electro vision. short female body figure." \
  --snr_gamma 5.0 \
  --noise_offset 0.03 \
  --num_validation_images=3 \
  --validation_epochs=400 \
  --resolution=512 \
  --train_batch_size=1 \
  --image_interpolation_mode lanczos \
  --learning_rate=2e-5 \
  --lr_scheduler="cosine" \
  --lr_warmup_steps=200 \
  --report_to="wandb" \
  --resume_from_checkpoint="latest" \
  --dataloader_num_workers=8 \
  --allow_tf32 \
  --mixed_precision="fp16" \
  --output_dir="/home/ubuntu/3w_2/" \
  --report_to="wandb"

